# Generated by Django 4.1 on 2022-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('user_interface', '0003_user_subscribed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_categories',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
    ]
