# Generated by Django 4.1 on 2022-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_interface", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
