# Generated by Django 4.1 on 2022-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("user_interface", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed_categories",
            field=models.ManyToManyField(to="categories.category"),
        ),
    ]
