# Generated by Django 4.1 on 2022-08-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publishing_year',
        ),
    ]
