# Generated by Django 4.1 on 2022-08-31 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_badword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="blog_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blog_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
