# Generated by Django 4.1 on 2022-08-30 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=240)),
                ('reply_body', models.TextField()),
                ('reply_created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('reply_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_post', to='posts.post')),
            ],
        ),
    ]
