# Generated by Django 4.1 on 2022-08-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_comment_reply_reply_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='com_reply',
        ),
    ]
