# Generated by Django 4.1 on 2022-08-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_reply_reply_com_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='com_reply',
            new_name='reply',
        ),
    ]
